on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@master
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.azureCredentials }}

    - name: Create ACR
      id: create-acr
      run: |
        az acr create -n azurek8slabcr -g azurek8slabcr838d-rg --location "West Europe" --sku Standard --admin-enabled
        echo "::set-output name=acr_username::`az acr credential show -n azurek8slabcr --query username | xargs`"
        echo "::set-output name=acr_password::`az acr credential show -n azurek8slabcr --query passwords[0].value | xargs`"
        echo "::add-mask::`az acr credential show -n azurek8slabcr --query passwords[0].value | xargs`"

    - uses: azure/docker-login@v1
      with:
        login-server: azurek8slabcr.azurecr.io
        username: ${{ steps.create-acr.outputs.acr_username }}
        password: ${{ steps.create-acr.outputs.acr_password }}

    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/azure-vote" -f  "azure-vote/Dockerfile" -t azurek8slabcr.azurecr.io/azurek8slabaks:${{ github.sha }}
        docker push azurek8slabcr.azurecr.io/azurek8slabaks:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      id: login
      with:
         kubeconfig: ${{ secrets.aks_azurek8slabaks_kubeConfig }}
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep azurek8slabaks032d | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace azurek8slabaks032d`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: azurek8slabaks032d
        container-registry-url: azurek8slabcr.azurecr.io
        container-registry-username: ${{ steps.create-acr.outputs.acr_username }}
        container-registry-password: ${{ steps.create-acr.outputs.acr_password }}
        secret-name: azurek8slabadockerauth
       
    - uses: azure/k8s-deploy@v1
      with:
        namespace: azurek8slabaks032d
        manifests: |
          manifests/deployment.yml
          manifests/service.yml
          manifests/ingress.yml
        images: |
          azurek8slabcr.azurecr.io/azurek8slabaks:${{ github.sha }}
        imagepullsecrets: |
          azurek8slabadockerauth